export const CartActionTypes = {
    TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART'
};