const ShopActionTypes = {
    FETCH_COLLECTIONS_STARTED: 'FETCH_COLLECTIONS_STARTED',
    FETCH_COLLECTIONS_SUCCEEDED: 'FETCH_COLLECTIONS_SUCCEEDED',
    FETCH_COLLECTIONS_FAILED: 'FETCH_COLLECTIONS_FAILED'
};

export default ShopActionTypes;